config/routes.rb
Rails.application.routes.draw do
  resources :quotes

  resources :customers

  resources :inventories

  resources :employees

   root 'inventories#index'

end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :employee
  belongs_to :customer
  belongs_to :inventory

end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:customer_id, :employee_id, :vehicle_id, :final_price, :status, :date)
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= form_for(@quote) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.collection_select :customer_id, Customer.all, :id, :cust_name %>
  </div>
  <div class="field">
    <%= f.label :employee_id %><br>
    <%= f.collection_select :employee_id, Employee.all, :id, :emp_name %>
  </div>
  <div class="field">
    <%= f.label :vehicle_id %><br>
    <%= f.collection_select :vehicle_id, Inventory.all, :id, :vehicle %>
  </div>
  <div class="field">
    <%= f.label :final_price %><br>
    <%= f.text_field :final_price %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.select :status, [['Pending','Pending'], ['Sold','Sold']] %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customer Quotes</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Employee</th>
      <th>Vehicle</th>
      <th>Final price</th>
      <th>Status</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.customer.cust_name %></td>
        <td><%= quote.employee.emp_name %></td>
        <td><%= quote.vehicle_id %></td>
        <td><%= quote.final_price %></td>
        <td><%= quote.status %></td>
        <td><%= quote.date %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path %>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form' %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @quote.customer.cust_name %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @quote.employee.emp_name %>
</p>

<p>
  <strong>Vehicle:</strong>
  <%= @quote.vehicle_id %>
</p>

<p>
  <strong>Final price:</strong>
  <%= @quote.final_price %>
</p>

<p>
  <strong>Status:</strong>
  <%= @quote.status %>
</p>

<p>
  <strong>Date:</strong>
  <%= @quote.date %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>