config/routes.rb
Rails.application.routes.draw do
  resources :quotes

  resources :customers

  resources :inventories

  resources :employees

   root 'inventories#index'

end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  has_many :quotes

  def vehicle
    "#{color} | #{make} | #{model} | VIN: #{vin_number}"
  end

  validates :vin_number, :presence => true
  validates :year, :presence => true

  def markup
    self.wholesale_price.to_s.to_d * (1.10)
  end

  def tax_price
    self.markup_price.to_s.to_d * (1.043)
  end

  def self.search(search)
    where ['color LIKE ? OR model LIKE ? OR vin_number LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%" ]
  end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: [:show, :edit, :update, :destroy]

  # GET /inventories
  # GET /inventories.json
  def index
    @inventories = Inventory.search(params[:search])
  end

  # GET /inventories/1
  # GET /inventories/1.json
  def show
  end

  # GET /inventories/new
  def new
    @inventory = Inventory.new
  end

  # GET /inventories/1/edit
  def edit
  end

  # POST /inventories
  # POST /inventories.json
  def create
    @inventory = Inventory.new(inventory_params)

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to @inventory, notice: 'Inventory was successfully created.' }
        format.json { render :show, status: :created, location: @inventory }
      else
        format.html { render :new }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventories/1
  # PATCH/PUT /inventories/1.json
  def update
    respond_to do |format|
      if @inventory.update(inventory_params)
        format.html { redirect_to @inventory, notice: 'Inventory was successfully updated.' }
        format.json { render :show, status: :ok, location: @inventory }
      else
        format.html { render :edit }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1
  # DELETE /inventories/1.json
  def destroy
    @inventory.destroy
    respond_to do |format|
      format.html { redirect_to inventories_url, notice: 'Inventory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inventory_params
      params.require(:inventory).permit(:make, :model, :year, :color, :transmission, :wholesale_price, :markup_price, :status, :vin_number)
    end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/_form.html.erb
<%= form_for(@inventory) do |f| %>
    <% if @inventory.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

          <ul>
            <% @inventory.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :make %><br>
      <%= f.text_field :make %>
    </div>
    <div class="field">
      <%= f.label :model %><br>
      <%= f.text_field :model %>
    </div>
    <div class="field">
      <%= f.label :year %><br>
      <%= f.number_field :year %>
    </div>
    <div class="field">
      <%= f.label :color %><br>
      <%= f.select :color, [['Red'],['Orange'],['Blue'],['Yellow'],['Brown'],['Beige'],['Green'],['White'],['Black'],['Silver'],['Grey'],['Purple'],['Light Blue'],['Seafoam']] %>
    </div>
    <div class="field">
      <%= f.label :transmission %><br>
      <%= f.select :transmission, [['Automatic'],['Manual']] %>
    </div>
    <div class="field">
      <%= f.label :wholesale_price %><br>
      <%= f.text_field :wholesale_price %>
    </div>
    <%#<div class="field">
    <%= f.label :markup_price %><%#<br>
    <%= f.text_field :markup
  <%#</div>%>
    <%#<div class="field">
      <%= f.label :status %>
     <%# <%= f.select :status, [['Available'],['Unavailable']] %>
    <%#</div>%>
    <div class="field">
      <%= f.label :vin_number %><br>
      <%= f.text_field :vin_number %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/inventories/edit.html.erb
<h1>Editing Inventory</h1>

<%= render 'form' %>

<%= link_to 'Show', @inventory %> |
<%= link_to 'Back', inventories_path %>

app/views/inventories/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag(inventories_path, :method => "get", class: "navbar-form", id: "search-form") do %>
    <div class="input-append">
      <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Search Inventory" %>
      <%= submit_tag "Search", :name => nil %>
    </div>
<% end %>

<h1>Inventory</h1>

<table>
  <thead>
  <tr>
    <th>Make</th>
    <th>Model</th>
    <th>Year</th>
    <th>Color</th>
    <th>Transmission</th>
    <th>Wholesale price</th>
    <th>Markup price</th>
    <th>Sell Price (with Tax)</th>
    <%# <th>Status</th> %>
    <th>VIN number</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @inventories.each do |inventory| %>
      <tr>
        <td><%= inventory.make %></td>
        <td><%= inventory.model %></td>
        <td><%= inventory.year %></td>
        <td><%= inventory.color %></td>
        <td><%= inventory.transmission %></td>
        <td><%= inventory.wholesale_price %></td>
        <td><%= inventory.markup %></td>
        <td><%= inventory.tax_price %></td>
        <%#<td><%= inventory.status %><%#</td>%>
        <td><%= inventory.vin_number %></td>
        <td><%= link_to 'Show', inventory %></td>
        <td><%= link_to 'Edit', edit_inventory_path(inventory) %></td>
        <td><%= link_to 'Destroy', inventory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inventory', new_inventory_path %>

app/views/inventories/new.html.erb
<h1>New Inventory</h1>

<%= render 'form' %>

<%= link_to 'Back', inventories_path %>

app/views/inventories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Make:</strong>
  <%= @inventory.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @inventory.model %>
</p>

<p>
  <strong>Year:</strong>
  <%= @inventory.year %>
</p>

<p>
  <strong>Color:</strong>
  <%= @inventory.color %>
</p>

<p>
  <strong>Transmission:</strong>
  <%= @inventory.transmission %>
</p>

<p>
  <strong>Wholesale price:</strong>
  <%= @inventory.wholesale_price %>
</p>

<p>
  <strong>Markup price:</strong>
  <%= @inventory.markup_price %>
</p>

<p>
  <strong>Sell Price with Tax:</strong>
  <%= @inventory.tax_price %>
</p>

<%#<p>
  <strong>Status:</strong>
  <%= @inventory.status %>
<%#</p>%>

<p>
  <strong>Vin number:</strong>
  <%= @inventory.vin_number %>
</p>

<%= link_to 'Edit', edit_inventory_path(@inventory) %> |
<%= link_to 'Back', inventories_path %>