config/routes.rb
Rails.application.routes.draw do
  resources :quotes

  resources :customers

  resources :inventories

  resources :employees

   root 'inventories#index'

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :quotes

  def emp_name
    "#{emp_lname}, #{emp_fname}"
  end

  def self.search(search)
    where ['emp_lname LIKE ? OR emp_fname LIKE ?', "%#{search}%", "%#{search}%" ]
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.search(params[:search])
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:emp_fname, :emp_lname, :emp_phone)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :emp_fname %><br>
    <%= f.text_field :emp_fname %>
  </div>
  <div class="field">
    <%= f.label :emp_lname %><br>
    <%= f.text_field :emp_lname %>
  </div>
  <div class="field">
    <%= f.label :emp_phone %><br>
    <%= f.text_field :emp_phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag(employees_path, :method => "get", class: "navbar-form", id: "search-form") do %>
    <div class="input-append">
      <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Search Employees" %>
      <%= submit_tag "Search", :name => nil %>
    </div>
<% end %>

<h1>Employees</h1>

<table>
  <thead>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Phone Number</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.emp_fname %></td>
        <td><%= employee.emp_lname %></td>
        <td><%= employee.emp_phone %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Emp fname:</strong>
  <%= @employee.emp_fname %>
</p>

<p>
  <strong>Emp lname:</strong>
  <%= @employee.emp_lname %>
</p>

<p>
  <strong>Emp phone:</strong>
  <%= @employee.emp_phone %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>