config/routes.rb
Rails.application.routes.draw do
  resources :quotes

  resources :customers

  resources :inventories

  resources :employees

   root 'inventories#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :quotes

  def cust_name
    "#{cust_lname}, #{cust_fname}"
  end

  def self.search(search)
    where ['cust_lname LIKE ? OR cust_fname LIKE ?', "%#{search}%", "%#{search}%" ]
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.search(params[:search])
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:cust_fname, :cust_lname, :cust_phone, :cust_email, :cust_address, :cust_city, :cust_state, :cust_zip)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
    <% if @customer.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

          <ul>
            <% @customer.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :First_Name %><br>
      <%= f.text_field :cust_fname %>
    </div>
    <div class="field">
      <%= f.label :Last_Name %><br>
      <%= f.text_field :cust_lname %>
    </div>
    <div class="field">
      <%= f.label :Phone_Number %><br>
      <%= f.text_field :cust_phone %>
    </div>
    <div class="field">
      <%= f.label :Email_Address %><br>
      <%= f.text_field :cust_email %>
    </div>
    <div class="field">
      <%= f.label :Street_Address %><br>
      <%= f.text_field :cust_address %>
    </div>
    <div class="field">
      <%= f.label :City %><br>
      <%= f.text_field :cust_city %>
    </div>
    <div class="field">
      <%= f.label :State %><br>
      <%= f.select :cust_state, [['AK', 'AK'], ['AL', 'AL'], ['AR', 'AR'], ['AZ', 'AZ'], ['CA', 'CA'], ['CO', 'CO'], ['CT', 'CT'], ['DC', 'DC'], ['DE', 'DE'], ['FL', 'FL'], ['GA', 'GA'], ['HI', 'HI'], ['IA', 'IA'], ['ID', 'ID'], ['IL', 'IL'], ['IN', 'IN'], ['KS', 'KS'], ['KY', 'KY'], ['LA', 'LA'], ['MA', 'MA'], ['MD', 'MD'], ['ME', 'ME'], ['MI', 'MI'], ['MN', 'MN'], ['MO', 'MO'], ['MS', 'MS'], ['MT', 'MT'], ['NC', 'NC'], ['ND', 'ND'], ['NE', 'NE'], ['NH', 'NH'], ['NJ', 'NJ'], ['NM', 'NM'], ['NV', 'NV'], ['NY', 'NY'], ['OH', 'OH'], ['OK', 'OK'], ['OR', 'OR'], ['PA', 'PA'], ['RI', 'RI'], ['SC', 'SC'], ['SD', 'SD'], ['TN', 'TN'], ['TX', 'TX'], ['UT', 'UT'], ['VA', 'VA'], ['VT', 'VT'], ['WA', 'WA'], ['WI', 'WI'], ['WV', 'WV'], ['WY', 'WY']] %>
    </div>
    <div class="field">
      <%= f.label :Zip_Code %><br>
      <%= f.text_field :cust_zip %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag(customers_path, :method => "get", class: "navbar-form", id: "search-form") do %>
    <div class="input-append">
      <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Search Customers" %>
      <%= submit_tag "Search", :name => nil %>
    </div>
<% end %>

<h1>Customers</h1>

<table>
  <thead>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Phone</th>
    <th>Email Address</th>
    <th>Street Address</th>
    <th>City</th>
    <th>State</th>
    <th>Zip Code</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.cust_fname %></td>
        <td><%= customer.cust_lname %></td>
        <td><%= customer.cust_phone %></td>
        <td><%= customer.cust_email %></td>
        <td><%= customer.cust_address %></td>
        <td><%= customer.cust_city %></td>
        <td><%= customer.cust_state %></td>
        <td><%= customer.cust_zip %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cust fname:</strong>
  <%= @customer.cust_fname %>
</p>

<p>
  <strong>Cust lname:</strong>
  <%= @customer.cust_lname %>
</p>

<p>
  <strong>Cust phone:</strong>
  <%= @customer.cust_phone %>
</p>

<p>
  <strong>Cust email:</strong>
  <%= @customer.cust_email %>
</p>

<p>
  <strong>Cust address:</strong>
  <%= @customer.cust_address %>
</p>

<p>
  <strong>Cust city:</strong>
  <%= @customer.cust_city %>
</p>

<p>
  <strong>Cust state:</strong>
  <%= @customer.cust_state %>
</p>

<p>
  <strong>Cust zip:</strong>
  <%= @customer.cust_zip %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>